// Auto-generated agent data
// Generated by scripts/parse-agents.mjs
// Do not edit manually

import { primaryAgents, commandAgents } from './primary-agents'

export const divisions = [
  "Academic",
  "Design",
  "Engineering",
  "Game Development",
  "Marketing",
  "Product",
  "Sales",
  "Spatial Computing",
  "Support",
  "Testing"
]

export const subAgents = [
  {
    "id": "historian",
    "name": "Historian",
    "description": "Expert in historical analysis, periodization, material culture, and historiography — validates historical coherence and enriches settings with authentic period detail grounded in primary and secondary sources",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Academic",
    "mode": "subagent"
  },
  {
    "id": "accessibility-auditor",
    "name": "Accessibility Auditor",
    "description": "Expert accessibility specialist who audits interfaces against WCAG standards, tests with assistive technologies, and ensures inclusive design. Defaults to finding barriers — if it's not tested with a screen reader, it's not accessible.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Design",
    "mode": "subagent"
  },
  {
    "id": "analytics-reporter",
    "name": "Analytics Reporter",
    "description": "Expert data analyst transforming raw data into actionable business insights. Creates dashboards, performs statistical analysis, tracks KPIs, and provides strategic decision support through data visualization and reporting.",
    "color": "#008080",
    "emoji": "📊",
    "division": "Design",
    "mode": "subagent"
  },
  {
    "id": "anthropologist",
    "name": "Anthropologist",
    "description": "Expert in cultural systems, rituals, kinship, belief systems, and ethnographic method — builds culturally coherent societies that feel lived-in rather than invented",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Design",
    "mode": "subagent"
  },
  {
    "id": "document-generator",
    "name": "Document Generator",
    "description": "Expert document creation specialist who generates professional PDF, PPTX, DOCX, and XLSX files using code-based approaches with proper formatting, charts, and data visualization.",
    "color": "#3498DB",
    "emoji": "📄",
    "division": "Design",
    "mode": "subagent"
  },
  {
    "id": "evidence-collector",
    "name": "Evidence Collector",
    "description": "Screenshot-obsessed, fantasy-allergic QA specialist - Default to finding 3-5 issues, requires visual proof for everything",
    "color": "#F39C12",
    "emoji": "👤",
    "division": "Design",
    "mode": "subagent"
  },
  {
    "id": "executive-summary-generator",
    "name": "Executive Summary Generator",
    "description": "Consultant-grade AI specialist trained to think and communicate like a senior strategy consultant. Transforms complex business inputs into concise, actionable executive summaries using McKinsey SCQA, BCG Pyramid Principle, and Bain frameworks for C-suite decision-makers.",
    "color": "#9B59B6",
    "emoji": "👤",
    "division": "Design",
    "mode": "subagent"
  },
  {
    "id": "geographer",
    "name": "Geographer",
    "description": "Expert in physical and human geography, climate systems, cartography, and spatial analysis — builds geographically coherent worlds where terrain, climate, resources, and settlement patterns make scientific sense",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Design",
    "mode": "subagent"
  },
  {
    "id": "inclusive-visuals-specialist",
    "name": "Inclusive Visuals Specialist",
    "description": "Representation expert who defeats systemic AI biases to generate culturally accurate, affirming, and non-stereotypical images and video.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Design",
    "mode": "subagent"
  },
  {
    "id": "psychologist",
    "name": "Psychologist",
    "description": "Expert in human behavior, personality theory, motivation, and cognitive patterns — builds psychologically credible characters and interactions grounded in clinical and research frameworks",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Design",
    "mode": "subagent"
  },
  {
    "id": "reality-checker",
    "name": "Reality Checker",
    "description": "Stops fantasy approvals, evidence-based certification - Default to \"NEEDS WORK\", requires overwhelming proof for production readiness",
    "color": "#E74C3C",
    "emoji": "👤",
    "division": "Design",
    "mode": "subagent"
  },
  {
    "id": "recruitment-specialist",
    "name": "Recruitment Specialist",
    "description": "Expert recruitment operations and talent acquisition specialist — skilled in China's major hiring platforms, talent assessment frameworks, and labor law compliance. Helps companies efficiently attract, screen, and retain top talent while building a competitive employer brand.",
    "color": "#3498DB",
    "emoji": "🎨",
    "division": "Design",
    "mode": "subagent"
  },
  {
    "id": "senior-project-manager",
    "name": "Senior Project Manager",
    "description": "Converts specs to tasks and remembers previous projects. Focused on realistic scope, no background processes, exact spec requirements",
    "color": "#3498DB",
    "emoji": "👤",
    "division": "Design",
    "mode": "subagent"
  },
  {
    "id": "ui-designer",
    "name": "UI Designer",
    "description": "Expert UI designer specializing in visual design systems, component libraries, and pixel-perfect interface creation. Creates beautiful, consistent, accessible user interfaces that enhance UX and reflect brand identity",
    "color": "#9B59B6",
    "emoji": "🎨",
    "division": "Design",
    "mode": "subagent"
  },
  {
    "id": "ux-researcher",
    "name": "UX Researcher",
    "description": "Expert user experience researcher specializing in user behavior analysis, usability testing, and data-driven design insights. Provides actionable research findings that improve product usability and user satisfaction",
    "color": "#2ECC71",
    "emoji": "🔍",
    "division": "Design",
    "mode": "subagent"
  },
  {
    "id": "whimsy-injector",
    "name": "Whimsy Injector",
    "description": "Expert creative specialist focused on adding personality, delight, and playful elements to brand experiences. Creates memorable, joyful interactions that differentiate brands through unexpected moments of whimsy",
    "color": "#E84393",
    "emoji": "👤",
    "division": "Design",
    "mode": "subagent"
  },
  {
    "id": "zk-steward",
    "name": "ZK Steward",
    "description": "Knowledge-base steward in the spirit of Niklas Luhmann's Zettelkasten. Default perspective: Luhmann; switches to domain experts (Feynman, Munger, Ogilvy, etc.) by task. Enforces atomic notes, connectivity, and validation loops. Use for knowledge-base building, note linking, complex task breakdown, and cross-domain decision support.",
    "color": "#008080",
    "emoji": "👤",
    "division": "Design",
    "mode": "subagent"
  },
  {
    "id": "accounts-payable-agent",
    "name": "Accounts Payable Agent",
    "description": "Autonomous payment processing specialist that executes vendor payments, contractor invoices, and recurring bills across any payment rail — crypto, fiat, stablecoins. Integrates with AI agent workflows via tool calls.",
    "color": "#2ECC71",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "ad-creative-strategist",
    "name": "Ad Creative Strategist",
    "description": "Paid media creative specialist focused on ad copywriting, RSA optimization, asset group design, and creative testing frameworks across Google, Meta, Microsoft, and programmatic platforms. Bridges the gap between performance data and persuasive messaging.",
    "color": "#F39C12",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "agentic-identity-trust-architect",
    "name": "Agentic Identity & Trust Architect",
    "description": "Designs identity, authentication, and trust verification systems for autonomous AI agents operating in multi-agent environments. Ensures agents can prove who they are, what they're authorized to do, and what they actually did.",
    "color": "#6B7280",
    "emoji": "🏛️",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "agents-orchestrator",
    "name": "Agents Orchestrator",
    "description": "Autonomous pipeline manager that orchestrates the entire development workflow. You are the leader of this process.",
    "color": "#00FFFF",
    "emoji": "🎭",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "ai-citation-strategist",
    "name": "AI Citation Strategist",
    "description": "Expert in AI recommendation engine optimization (AEO/GEO) — audits brand visibility across ChatGPT, Claude, Gemini, and Perplexity, identifies why competitors get cited instead, and delivers content fixes that improve AI citations",
    "color": "#6B7280",
    "emoji": "🤖",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "ai-data-remediation-engineer",
    "name": "AI Data Remediation Engineer",
    "description": "Specialist in self-healing data pipelines — uses air-gapped local SLMs and semantic clustering to automatically detect, classify, and fix data anomalies at scale. Focuses exclusively on the remediation layer: intercepting bad data, generating deterministic fix logic via Ollama, and guaranteeing zero data loss. Not a general data engineer — a surgical specialist for when your data is broken and the pipeline can't stop.",
    "color": "#2ECC71",
    "emoji": "🤖",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "ai-engineer",
    "name": "AI Engineer",
    "description": "Expert AI/ML engineer specializing in machine learning model development, deployment, and integration into production systems. Focused on building intelligent features, data pipelines, and AI-powered applications with emphasis on practical, scalable solutions.",
    "color": "#3498DB",
    "emoji": "🤖",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "app-store-optimizer",
    "name": "App Store Optimizer",
    "description": "Expert app store marketing specialist focused on App Store Optimization (ASO), conversion rate optimization, and app discoverability",
    "color": "#3498DB",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "automation-governance-architect",
    "name": "Automation Governance Architect",
    "description": "Governance-first architect for business automations (n8n-first) who audits value, risk, and maintainability before implementation.",
    "color": "#00FFFF",
    "emoji": "🏛️",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "autonomous-optimization-architect",
    "name": "Autonomous Optimization Architect",
    "description": "Intelligent system governor that continuously shadow-tests APIs for performance while enforcing strict financial and security guardrails against runaway costs.",
    "color": "#6B7280",
    "emoji": "🏛️",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "backend-architect",
    "name": "Backend Architect",
    "description": "Senior backend architect specializing in scalable system design, database architecture, API development, and cloud infrastructure. Builds robust, secure, performant server-side applications and microservices",
    "color": "#3498DB",
    "emoji": "🏗️",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "baidu-seo-specialist",
    "name": "Baidu SEO Specialist",
    "description": "Expert Baidu search optimization specialist focused on Chinese search engine ranking, Baidu ecosystem integration, ICP compliance, Chinese keyword research, and mobile-first indexing for the China market.",
    "color": "#3498DB",
    "emoji": "🤖",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "bilibili-content-strategist",
    "name": "Bilibili Content Strategist",
    "description": "Expert Bilibili marketing specialist focused on UP主 growth, danmaku culture mastery, B站 algorithm optimization, community building, and branded content strategy for China's leading video community platform.",
    "color": "#E84393",
    "emoji": "📝",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "blender-add-on-engineer",
    "name": "Blender Add-on Engineer",
    "description": "Blender tooling specialist - Builds Python add-ons, asset validators, exporters, and pipeline automations that turn repetitive DCC work into reliable one-click workflows",
    "color": "#3498DB",
    "emoji": "🎨",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "blockchain-security-auditor",
    "name": "Blockchain Security Auditor",
    "description": "Expert smart contract security auditor specializing in vulnerability detection, formal verification, exploit analysis, and comprehensive audit report writing for DeFi protocols and blockchain applications.",
    "color": "#E74C3C",
    "emoji": "🤖",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "carousel-growth-engine",
    "name": "Carousel Growth Engine",
    "description": "Autonomous TikTok and Instagram carousel generation specialist. Analyzes any website URL with Playwright, generates viral 6-slide carousels via Gemini image generation, publishes directly to feed via Upload-Post API with auto trending music, fetches analytics, and iteratively improves through a data-driven learning loop.",
    "color": "#6B7280",
    "emoji": "📈",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "china-e-commerce-operator",
    "name": "China E-Commerce Operator",
    "description": "Expert China e-commerce operations specialist covering Taobao, Tmall, Pinduoduo, and JD ecosystems with deep expertise in product listing optimization, live commerce, store operations, 618/Double 11 campaigns, and cross-platform strategy.",
    "color": "#E74C3C",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "code-reviewer",
    "name": "Code Reviewer",
    "description": "Expert code reviewer who provides constructive, actionable feedback focused on correctness, maintainability, security, and performance — not style preferences.",
    "color": "#9B59B6",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "compliance-auditor",
    "name": "Compliance Auditor",
    "description": "Expert technical compliance auditor specializing in SOC 2, ISO 27001, HIPAA, and PCI-DSS audits — from readiness assessment through evidence collection to certification.",
    "color": "#F39C12",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "corporate-training-designer",
    "name": "Corporate Training Designer",
    "description": "Expert in enterprise training system design and curriculum development — proficient in training needs analysis, instructional design methodology, blended learning program design, internal trainer development, leadership programs, and training effectiveness evaluation and continuous optimization.",
    "color": "#F39C12",
    "emoji": "🤖",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "cross-border-e-commerce-specialist",
    "name": "Cross-Border E-Commerce Specialist",
    "description": "Full-funnel cross-border e-commerce strategist covering Amazon, Shopee, Lazada, AliExpress, Temu, and TikTok Shop operations, international logistics and overseas warehousing, compliance and taxation, multilingual listing optimization, brand globalization, and DTC independent site development.",
    "color": "#3498DB",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "data-engineer",
    "name": "Data Engineer",
    "description": "Expert data engineer specializing in building reliable data pipelines, lakehouse architectures, and scalable data infrastructure. Masters ETL/ELT, Apache Spark, dbt, streaming systems, and cloud data platforms to turn raw data into trusted, analytics-ready assets.",
    "color": "#F39C12",
    "emoji": "📈",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "database-optimizer",
    "name": "Database Optimizer",
    "description": "Expert database specialist focusing on schema design, query optimization, indexing strategies, and performance tuning for PostgreSQL, MySQL, and modern databases like Supabase and PlanetScale.",
    "color": "#F59E0B",
    "emoji": "📈",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "developer-advocate",
    "name": "Developer Advocate",
    "description": "Expert developer advocate specializing in building developer communities, creating compelling technical content, optimizing developer experience (DX), and driving platform adoption through authentic engineering engagement. Bridges product and engineering teams with external developers.",
    "color": "#9B59B6",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "devops-automator",
    "name": "DevOps Automator",
    "description": "Expert DevOps engineer specializing in infrastructure automation, CI/CD pipeline development, and cloud operations",
    "color": "#F39C12",
    "emoji": "🚀",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "embedded-firmware-engineer",
    "name": "Embedded Firmware Engineer",
    "description": "Specialist in bare-metal and RTOS firmware - ESP32/ESP-IDF, PlatformIO, Arduino, ARM Cortex-M, STM32 HAL/LL, Nordic nRF5/nRF Connect SDK, FreeRTOS, Zephyr",
    "color": "#F39C12",
    "emoji": "🔌",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "feishu-integration-developer",
    "name": "Feishu Integration Developer",
    "description": "Full-stack integration expert specializing in the Feishu (Lark) Open Platform — proficient in Feishu bots, mini programs, approval workflows, Bitable (multidimensional spreadsheets), interactive message cards, Webhooks, SSO authentication, and workflow automation, building enterprise-grade collaboration and automation solutions within the Feishu ecosystem.",
    "color": "#3498DB",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "frontend-developer",
    "name": "Frontend Developer",
    "description": "Expert frontend developer specializing in modern web technologies, React/Vue/Angular frameworks, UI implementation, and performance optimization",
    "color": "#00FFFF",
    "emoji": "🖥️",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "game-audio-engineer",
    "name": "Game Audio Engineer",
    "description": "Interactive audio specialist - Masters FMOD/Wwise integration, adaptive music systems, spatial audio, and audio performance budgeting across all game engines",
    "color": "#6366F1",
    "emoji": "🎮",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "game-designer",
    "name": "Game Designer",
    "description": "Systems and mechanics architect - Masters GDD authorship, player psychology, economy balancing, and gameplay loop design across all engines and genres",
    "color": "#EAB308",
    "emoji": "🎨",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "godot-gameplay-scripter",
    "name": "Godot Gameplay Scripter",
    "description": "Composition and signal integrity specialist - Masters GDScript 2.0, C# integration, node-based architecture, and type-safe signal design for Godot 4 projects",
    "color": "#9B59B6",
    "emoji": "🎮",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "godot-multiplayer-engineer",
    "name": "Godot Multiplayer Engineer",
    "description": "Godot 4 networking specialist - Masters the MultiplayerAPI, scene replication, ENet/WebRTC transport, RPCs, and authority models for real-time multiplayer games",
    "color": "#8B5CF6",
    "emoji": "🎮",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "godot-shader-developer",
    "name": "Godot Shader Developer",
    "description": "Godot 4 visual effects specialist - Masters the Godot Shading Language (GLSL-like), VisualShader editor, CanvasItem and Spatial shaders, post-processing, and performance optimization for 2D/3D effects",
    "color": "#9B59B6",
    "emoji": "✨",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "government-digital-presales-consultant",
    "name": "Government Digital Presales Consultant",
    "description": "Presales expert for China's government digital transformation market (ToG), proficient in policy interpretation, solution design, bid document preparation, POC validation, compliance requirements (classified protection/cryptographic assessment/Xinchuang domestic IT), and stakeholder management — helping technical teams efficiently win government IT projects.",
    "color": "#6B7280",
    "emoji": "💼",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "growth-hacker",
    "name": "Growth Hacker",
    "description": "Expert growth strategist specializing in rapid user acquisition through data-driven experimentation. Develops viral loops, optimizes conversion funnels, and finds scalable growth channels for exponential business growth.",
    "color": "#2ECC71",
    "emoji": "📈",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "image-prompt-engineer",
    "name": "Image Prompt Engineer",
    "description": "Expert photography prompt engineer specializing in crafting detailed, evocative prompts for AI image generation. Masters the art of translating visual concepts into precise language that produces stunning, professional-quality photography through generative AI tools.",
    "color": "#F59E0B",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "incident-response-commander",
    "name": "Incident Response Commander",
    "description": "Expert incident commander specializing in production incident management, structured response coordination, post-mortem facilitation, SLO/SLI tracking, and on-call process design for reliable engineering organizations.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "infrastructure-maintainer",
    "name": "Infrastructure Maintainer",
    "description": "Expert infrastructure specialist focused on system reliability, performance optimization, and technical operations management. Maintains robust, scalable infrastructure supporting business operations with security, performance, and cost efficiency.",
    "color": "#F39C12",
    "emoji": "🤖",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "instagram-curator",
    "name": "Instagram Curator",
    "description": "Expert Instagram marketing specialist focused on visual storytelling, community building, and multi-format content optimization. Masters aesthetic development and drives meaningful engagement.",
    "color": "#6B7280",
    "emoji": "📸",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "kuaishou-strategist",
    "name": "Kuaishou Strategist",
    "description": "Expert Kuaishou marketing strategist specializing in short-video content for China's lower-tier city markets, live commerce operations, community trust building, and grassroots audience growth on 快手.",
    "color": "#F39C12",
    "emoji": "🤖",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "level-designer",
    "name": "Level Designer",
    "description": "Spatial storytelling and flow specialist - Masters layout theory, pacing architecture, encounter design, and environmental narrative across all game engines",
    "color": "#008080",
    "emoji": "🎨",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "linkedin-content-creator",
    "name": "LinkedIn Content Creator",
    "description": "Expert LinkedIn content strategist focused on thought leadership, personal brand building, and high-engagement professional content. Masters LinkedIn's algorithm and culture to drive inbound opportunities for founders, job seekers, developers, and anyone building a professional presence.",
    "color": "#6B7280",
    "emoji": "📝",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "livestream-commerce-coach",
    "name": "Livestream Commerce Coach",
    "description": "Veteran livestream e-commerce coach specializing in host training and live room operations across Douyin, Kuaishou, Taobao Live, and Channels, covering script design, product sequencing, paid-vs-organic traffic balancing, conversion closing techniques, and real-time data-driven optimization.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "lsp-index-engineer",
    "name": "LSP/Index Engineer",
    "description": "Language Server Protocol specialist building unified code intelligence systems through LSP client orchestration and semantic indexing",
    "color": "#F39C12",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "macos-spatial-metal-engineer",
    "name": "macOS Spatial/Metal Engineer",
    "description": "Native Swift and Metal specialist building high-performance 3D rendering systems and spatial computing experiences for macOS and Vision Pro",
    "color": "#3B82F6",
    "emoji": "🥽",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "mcp-builder",
    "name": "MCP Builder",
    "description": "Expert Model Context Protocol developer who designs, builds, and tests MCP servers that extend AI agent capabilities with custom tools, resources, and prompts.",
    "color": "#6366F1",
    "emoji": "🎨",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "mobile-app-builder",
    "name": "Mobile App Builder",
    "description": "Specialized mobile application developer with expertise in native iOS/Android development and cross-platform frameworks",
    "color": "#9B59B6",
    "emoji": "📱",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "narrative-designer",
    "name": "Narrative Designer",
    "description": "Story systems and dialogue architect - Masters GDD-aligned narrative design, branching dialogue, lore architecture, and environmental storytelling across all game engines",
    "color": "#E74C3C",
    "emoji": "🎨",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "performance-benchmarker",
    "name": "Performance Benchmarker",
    "description": "Expert performance testing and optimization specialist focused on measuring, analyzing, and improving system performance across all applications and infrastructure",
    "color": "#F39C12",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "ppc-campaign-strategist",
    "name": "PPC Campaign Strategist",
    "description": "Senior paid media strategist specializing in large-scale search, shopping, and performance max campaign architecture across Google, Microsoft, and Amazon ad platforms. Designs account structures, budget allocation frameworks, and bidding strategies that scale from $10K to $10M+ monthly spend.",
    "color": "#F39C12",
    "emoji": "🤖",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "private-domain-operator",
    "name": "Private Domain Operator",
    "description": "Expert in building enterprise WeChat (WeCom) private domain ecosystems, with deep expertise in SCRM systems, segmented community operations, Mini Program commerce integration, user lifecycle management, and full-funnel conversion optimization.",
    "color": "#6B7280",
    "emoji": "🤖",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "product-manager",
    "name": "Product Manager",
    "description": "Holistic product leader who owns the full product lifecycle — from discovery and strategy through roadmap, stakeholder alignment, go-to-market, and outcome measurement. Bridges business goals, user needs, and technical reality to ship the right thing at the right time.",
    "color": "#3498DB",
    "emoji": "📊",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "proposal-strategist",
    "name": "Proposal Strategist",
    "description": "Strategic proposal architect who transforms RFPs and sales opportunities into compelling win narratives. Specializes in win theme development, competitive positioning, executive summary craft, and building proposals that persuade rather than merely comply.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "rapid-prototyper",
    "name": "Rapid Prototyper",
    "description": "Specialized in ultra-fast proof-of-concept development and MVP creation using efficient tools and frameworks",
    "color": "#2ECC71",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "reddit-community-builder",
    "name": "Reddit Community Builder",
    "description": "Expert Reddit marketing specialist focused on authentic community engagement, value-driven content creation, and long-term relationship building. Masters Reddit culture navigation.",
    "color": "#6B7280",
    "emoji": "🤝",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "roblox-avatar-creator",
    "name": "Roblox Avatar Creator",
    "description": "Roblox UGC and avatar pipeline specialist - Masters Roblox's avatar system, UGC item creation, accessory rigging, texture standards, and the Creator Marketplace submission pipeline",
    "color": "#D946EF",
    "emoji": "🎮",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "roblox-experience-designer",
    "name": "Roblox Experience Designer",
    "description": "Roblox platform UX and monetization specialist - Masters engagement loop design, DataStore-driven progression, Roblox monetization systems (Passes, Developer Products, UGC), and player retention for Roblox experiences",
    "color": "#84CC16",
    "emoji": "🎨",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "roblox-systems-scripter",
    "name": "Roblox Systems Scripter",
    "description": "Roblox platform engineering specialist - Masters Luau, the client-server security model, RemoteEvents/RemoteFunctions, DataStore, and module architecture for scalable Roblox experiences",
    "color": "#F43F5E",
    "emoji": "🎮",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "sales-engineer",
    "name": "Sales Engineer",
    "description": "Senior pre-sales engineer specializing in technical discovery, demo engineering, POC scoping, competitive battlecards, and bridging product capabilities to business outcomes. Wins the technical decision so the deal can close.",
    "color": "#6B7280",
    "emoji": "💼",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "salesforce-architect",
    "name": "Salesforce Architect",
    "description": "Solution architecture for Salesforce platform — multi-cloud design, integration patterns, governor limits, deployment strategy, and data model governance for enterprise-scale orgs",
    "color": "#6B7280",
    "emoji": "💼",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "search-query-analyst",
    "name": "Search Query Analyst",
    "description": "Specialist in search term analysis, negative keyword architecture, and query-to-intent mapping. Turns raw search query data into actionable optimizations that eliminate waste and amplify high-intent traffic across paid search accounts.",
    "color": "#F39C12",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "security-engineer",
    "name": "Security Engineer",
    "description": "Expert application security engineer specializing in threat modeling, vulnerability assessment, secure code review, and security architecture design for modern web and cloud-native applications.",
    "color": "#E74C3C",
    "emoji": "🔒",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "senior-developer",
    "name": "Senior Developer",
    "description": "Premium implementation specialist - Masters Laravel/Livewire/FluxUI, advanced CSS, Three.js integration",
    "color": "#2ECC71",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "seo-specialist",
    "name": "SEO Specialist",
    "description": "Expert search engine optimization strategist specializing in technical SEO, content optimization, link authority building, and organic search growth. Drives sustainable traffic through data-driven search strategies.",
    "color": "#6B7280",
    "emoji": "🔎",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "short-video-editing-coach",
    "name": "Short-Video Editing Coach",
    "description": "Hands-on short-video editing coach covering the full post-production pipeline, with mastery of CapCut Pro, Premiere Pro, DaVinci Resolve, and Final Cut Pro across composition and camera language, color grading, audio engineering, motion graphics and VFX, subtitle design, multi-platform export optimization, editing workflow efficiency, and AI-assisted editing.",
    "color": "#6B7280",
    "emoji": "🎬",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "software-architect",
    "name": "Software Architect",
    "description": "Expert software architect specializing in system design, domain-driven design, architectural patterns, and technical decision-making for scalable, maintainable systems.",
    "color": "#6366F1",
    "emoji": "🏛️",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "solidity-smart-contract-engineer",
    "name": "Solidity Smart Contract Engineer",
    "description": "Expert Solidity developer specializing in EVM smart contract architecture, gas optimization, upgradeable proxy patterns, DeFi protocol development, and security-first contract design across Ethereum and L2 chains.",
    "color": "#F39C12",
    "emoji": "📜",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "sre-site-reliability-engineer",
    "name": "SRE (Site Reliability Engineer)",
    "description": "Expert site reliability engineer specializing in SLOs, error budgets, observability, chaos engineering, and toil reduction for production systems at scale.",
    "color": "#6B7280",
    "emoji": "🛡️",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "studio-operations",
    "name": "Studio Operations",
    "description": "Expert operations manager specializing in day-to-day studio efficiency, process optimization, and resource coordination. Focused on ensuring smooth operations, maintaining productivity standards, and supporting all teams with the tools and processes needed for success.",
    "color": "#2ECC71",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "studio-producer",
    "name": "Studio Producer",
    "description": "Senior strategic leader specializing in high-level creative and technical project orchestration, resource allocation, and multi-project portfolio management. Focused on aligning creative vision with business objectives while managing complex cross-functional initiatives and ensuring optimal studio operations.",
    "color": "#EAB308",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "support-responder",
    "name": "Support Responder",
    "description": "Expert customer support specialist delivering exceptional customer service, issue resolution, and user experience optimization. Specializes in multi-channel support, proactive customer care, and turning support interactions into positive brand experiences.",
    "color": "#3498DB",
    "emoji": "💬",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "technical-artist",
    "name": "Technical Artist",
    "description": "Art-to-engine pipeline specialist - Masters shaders, VFX systems, LOD pipelines, performance budgeting, and cross-engine asset optimization",
    "color": "#E84393",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "technical-writer",
    "name": "Technical Writer",
    "description": "Expert technical writer specializing in developer documentation, API references, README files, and tutorials. Transforms complex engineering concepts into clear, accurate, and engaging docs that developers actually read and use.",
    "color": "#008080",
    "emoji": "✍️",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "terminal-integration-specialist",
    "name": "Terminal Integration Specialist",
    "description": "Terminal emulation, text rendering optimization, and SwiftTerm integration for modern Swift applications",
    "color": "#2ECC71",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "threat-detection-engineer",
    "name": "Threat Detection Engineer",
    "description": "Expert detection engineer specializing in SIEM rule development, MITRE ATT&CK coverage mapping, threat hunting, alert tuning, and detection-as-code pipelines for security operations teams.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "tiktok-strategist",
    "name": "TikTok Strategist",
    "description": "Expert TikTok marketing specialist focused on viral content creation, algorithm optimization, and community building. Masters TikTok's unique culture and features for brand growth.",
    "color": "#6B7280",
    "emoji": "🎵",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "tool-evaluator",
    "name": "Tool Evaluator",
    "description": "Expert technology assessment specialist focused on evaluating, testing, and recommending tools, software, and platforms for business use and productivity optimization",
    "color": "#008080",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "tracking-measurement-specialist",
    "name": "Tracking & Measurement Specialist",
    "description": "Expert in conversion tracking architecture, tag management, and attribution modeling across Google Tag Manager, GA4, Google Ads, Meta CAPI, LinkedIn Insight Tag, and server-side implementations. Ensures every conversion is counted correctly and every dollar of ad spend is measurable.",
    "color": "#F39C12",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "trend-researcher",
    "name": "Trend Researcher",
    "description": "Expert market intelligence analyst specializing in identifying emerging trends, competitive analysis, and opportunity assessment. Focused on providing actionable insights that drive product strategy and innovation decisions.",
    "color": "#9B59B6",
    "emoji": "🔍",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "twitter-engager",
    "name": "Twitter Engager",
    "description": "Expert Twitter marketing specialist focused on real-time engagement, thought leadership building, and community-driven growth. Builds brand authority through authentic conversation participation and viral thread creation.",
    "color": "#6B7280",
    "emoji": "🐦",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "unity-architect",
    "name": "Unity Architect",
    "description": "Data-driven modularity specialist - Masters ScriptableObjects, decoupled systems, and single-responsibility component design for scalable Unity projects",
    "color": "#3498DB",
    "emoji": "🏛️",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "unity-editor-tool-developer",
    "name": "Unity Editor Tool Developer",
    "description": "Unity editor automation specialist - Masters custom EditorWindows, PropertyDrawers, AssetPostprocessors, ScriptedImporters, and pipeline automation that saves teams hours per week",
    "color": "#6B7280",
    "emoji": "🎮",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "unity-multiplayer-engineer",
    "name": "Unity Multiplayer Engineer",
    "description": "Networked gameplay specialist - Masters Netcode for GameObjects, Unity Gaming Services (Relay/Lobby), client-server authority, lag compensation, and state synchronization",
    "color": "#3498DB",
    "emoji": "🎮",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "unity-shader-graph-artist",
    "name": "Unity Shader Graph Artist",
    "description": "Visual effects and material specialist - Masters Unity Shader Graph, HLSL, URP/HDRP rendering pipelines, and custom pass authoring for real-time visual effects",
    "color": "#00FFFF",
    "emoji": "✨",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "unreal-multiplayer-architect",
    "name": "Unreal Multiplayer Architect",
    "description": "Unreal Engine networking specialist - Masters Actor replication, GameMode/GameState architecture, server-authoritative gameplay, network prediction, and dedicated server setup for UE5",
    "color": "#E74C3C",
    "emoji": "🏛️",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "unreal-systems-engineer",
    "name": "Unreal Systems Engineer",
    "description": "Performance and hybrid architecture specialist - Masters C++/Blueprint continuum, Nanite geometry, Lumen GI, and Gameplay Ability System for AAA-grade Unreal Engine projects",
    "color": "#F39C12",
    "emoji": "🎮",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "unreal-technical-artist",
    "name": "Unreal Technical Artist",
    "description": "Unreal Engine visual pipeline specialist - Masters the Material Editor, Niagara VFX, Procedural Content Generation, and the art-to-engine pipeline for UE5 projects",
    "color": "#F39C12",
    "emoji": "🎮",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "unreal-world-builder",
    "name": "Unreal World Builder",
    "description": "Open-world and environment specialist - Masters UE5 World Partition, Landscape, procedural foliage, HLOD, and large-scale level streaming for seamless open-world experiences",
    "color": "#2ECC71",
    "emoji": "🎨",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "ux-architect",
    "name": "UX Architect",
    "description": "Technical architecture and UX specialist who provides developers with solid foundations, CSS systems, and clear implementation guidance",
    "color": "#9B59B6",
    "emoji": "🏛️",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "visionos-spatial-engineer",
    "name": "visionOS Spatial Engineer",
    "description": "Native visionOS spatial computing, SwiftUI volumetric interfaces, and Liquid Glass design implementation",
    "color": "#6366F1",
    "emoji": "🥽",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "wechat-mini-program-developer",
    "name": "WeChat Mini Program Developer",
    "description": "Expert WeChat Mini Program developer specializing in 小程序 development with WXML/WXSS/WXS, WeChat API integration, payment systems, subscription messaging, and the full WeChat ecosystem.",
    "color": "#2ECC71",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "wechat-official-account-manager",
    "name": "WeChat Official Account Manager",
    "description": "Expert WeChat Official Account (OA) strategist specializing in content marketing, subscriber engagement, and conversion optimization. Masters multi-format content and builds loyal communities through consistent value delivery.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "weibo-strategist",
    "name": "Weibo Strategist",
    "description": "Full-spectrum operations expert for Sina Weibo, with deep expertise in trending topic mechanics, Super Topic community management, public sentiment monitoring, fan economy strategies, and Weibo advertising, helping brands achieve viral reach and sustained growth on China's leading public discourse platform.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "workflow-architect",
    "name": "Workflow Architect",
    "description": "Workflow design specialist who maps complete workflow trees for every system, user journey, and agent interaction — covering happy paths, all branch conditions, failure modes, recovery paths, handoff contracts, and observable states to produce build-ready specs that agents can implement against and QA can test against.",
    "color": "#F39C12",
    "emoji": "🏛️",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "xiaohongshu-specialist",
    "name": "Xiaohongshu Specialist",
    "description": "Expert Xiaohongshu marketing specialist focused on lifestyle content, trend-driven strategies, and authentic community engagement. Masters micro-content creation and drives viral growth through aesthetic storytelling.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "xr-immersive-developer",
    "name": "XR Immersive Developer",
    "description": "Expert WebXR and immersive technology developer with specialization in browser-based AR/VR/XR applications",
    "color": "#06B6D4",
    "emoji": "👓",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "xr-interface-architect",
    "name": "XR Interface Architect",
    "description": "Spatial interaction designer and interface strategist for immersive AR/VR/XR environments",
    "color": "#10B981",
    "emoji": "🏛️",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "zhihu-strategist",
    "name": "Zhihu Strategist",
    "description": "Expert Zhihu marketing specialist focused on thought leadership, community credibility, and knowledge-driven engagement. Masters question-answering strategy and builds brand authority through authentic expertise sharing.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Engineering",
    "mode": "subagent"
  },
  {
    "id": "narratologist",
    "name": "Narratologist",
    "description": "Expert in narrative theory, story structure, character arcs, and literary analysis — grounds advice in established frameworks from Propp to Campbell to modern narratology",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Game Development",
    "mode": "subagent"
  },
  {
    "id": "book-co-author",
    "name": "Book Co-Author",
    "description": "Strategic thought-leadership book collaborator for founders, experts, and operators turning voice notes, fragments, and positioning into structured first-person chapters.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Marketing",
    "mode": "subagent"
  },
  {
    "id": "content-creator",
    "name": "Content Creator",
    "description": "Expert content strategist and creator for multi-platform campaigns. Develops editorial calendars, creates compelling copy, manages brand storytelling, and optimizes content for engagement across all digital channels.",
    "color": "#008080",
    "emoji": "📝",
    "division": "Marketing",
    "mode": "subagent"
  },
  {
    "id": "douyin-strategist",
    "name": "Douyin Strategist",
    "description": "Short-video marketing expert specializing in the Douyin platform, with deep expertise in recommendation algorithm mechanics, viral video planning, livestream commerce workflows, and full-funnel brand growth through content matrix strategies.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Marketing",
    "mode": "subagent"
  },
  {
    "id": "finance-tracker",
    "name": "Finance Tracker",
    "description": "Expert financial analyst and controller specializing in financial planning, budget management, and business performance analysis. Maintains financial health, optimizes cash flow, and provides strategic financial insights for business growth.",
    "color": "#2ECC71",
    "emoji": "💰",
    "division": "Marketing",
    "mode": "subagent"
  },
  {
    "id": "healthcare-marketing-compliance-specialist",
    "name": "Healthcare Marketing Compliance Specialist",
    "description": "Expert in healthcare marketing compliance in China, proficient in the Advertising Law, Medical Advertisement Management Measures, Drug Administration Law, and related regulations — covering pharmaceuticals, medical devices, medical aesthetics, health supplements, and internet healthcare across content review, risk control, platform rule interpretation, and patient privacy protection, helping enterprises conduct effective health marketing within legal boundaries.",
    "color": "#6B7280",
    "emoji": "📢",
    "division": "Marketing",
    "mode": "subagent"
  },
  {
    "id": "legal-compliance-checker",
    "name": "Legal Compliance Checker",
    "description": "Expert legal and compliance specialist ensuring business operations, data handling, and content creation comply with relevant laws, regulations, and industry standards across multiple jurisdictions.",
    "color": "#E74C3C",
    "emoji": "⚖️",
    "division": "Marketing",
    "mode": "subagent"
  },
  {
    "id": "paid-social-strategist",
    "name": "Paid Social Strategist",
    "description": "Cross-platform paid social advertising specialist covering Meta (Facebook/Instagram), LinkedIn, TikTok, Pinterest, X, and Snapchat. Designs full-funnel social ad programs from prospecting through retargeting with platform-specific creative and audience strategies.",
    "color": "#F39C12",
    "emoji": "🤖",
    "division": "Marketing",
    "mode": "subagent"
  },
  {
    "id": "podcast-strategist",
    "name": "Podcast Strategist",
    "description": "Content strategy and operations expert for the Chinese podcast market, with deep expertise in Xiaoyuzhou, Ximalaya, and other major audio platforms, covering show positioning, audio production, audience growth, multi-platform distribution, and monetization to help podcast creators build sticky audio content brands.",
    "color": "#9B59B6",
    "emoji": "👤",
    "division": "Marketing",
    "mode": "subagent"
  },
  {
    "id": "programmatic-display-buyer",
    "name": "Programmatic & Display Buyer",
    "description": "Display advertising and programmatic media buying specialist covering managed placements, Google Display Network, DV360, trade desk platforms, partner media (newsletters, sponsored content), and ABM display strategies via platforms like Demandbase and 6Sense.",
    "color": "#F39C12",
    "emoji": "👤",
    "division": "Marketing",
    "mode": "subagent"
  },
  {
    "id": "social-media-strategist",
    "name": "Social Media Strategist",
    "description": "Expert social media strategist for LinkedIn, Twitter, and professional platforms. Creates cross-platform campaigns, builds communities, manages real-time engagement, and develops thought leadership strategies.",
    "color": "#3498DB",
    "emoji": "📱",
    "division": "Marketing",
    "mode": "subagent"
  },
  {
    "id": "visual-storyteller",
    "name": "Visual Storyteller",
    "description": "Expert visual communication specialist focused on creating compelling visual narratives, multimedia content, and brand storytelling through design. Specializes in transforming complex information into engaging visual stories that connect with audiences and drive emotional engagement.",
    "color": "#9B59B6",
    "emoji": "👤",
    "division": "Marketing",
    "mode": "subagent"
  },
  {
    "id": "behavioral-nudge-engine",
    "name": "Behavioral Nudge Engine",
    "description": "Behavioral psychology specialist that adapts software interaction cadences and styles to maximize user motivation and success.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Product",
    "mode": "subagent"
  },
  {
    "id": "experiment-tracker",
    "name": "Experiment Tracker",
    "description": "Expert project manager specializing in experiment design, execution tracking, and data-driven decision making. Focused on managing A/B tests, feature experiments, and hypothesis validation through systematic experimentation and rigorous analysis.",
    "color": "#9B59B6",
    "emoji": "👤",
    "division": "Product",
    "mode": "subagent"
  },
  {
    "id": "feedback-synthesizer",
    "name": "Feedback Synthesizer",
    "description": "Expert in collecting, analyzing, and synthesizing user feedback from multiple channels to extract actionable product insights. Transforms qualitative feedback into quantitative priorities and strategic recommendations.",
    "color": "#3498DB",
    "emoji": "👤",
    "division": "Product",
    "mode": "subagent"
  },
  {
    "id": "project-shepherd",
    "name": "Project Shepherd",
    "description": "Expert project manager specializing in cross-functional project coordination, timeline management, and stakeholder alignment. Focused on shepherding projects from conception to completion while managing resources, risks, and communications across multiple teams and departments.",
    "color": "#3498DB",
    "emoji": "👤",
    "division": "Product",
    "mode": "subagent"
  },
  {
    "id": "sprint-prioritizer",
    "name": "Sprint Prioritizer",
    "description": "Expert product manager specializing in agile sprint planning, feature prioritization, and resource allocation. Focused on maximizing team velocity and business value delivery through data-driven prioritization frameworks.",
    "color": "#2ECC71",
    "emoji": "👤",
    "division": "Product",
    "mode": "subagent"
  },
  {
    "id": "workflow-optimizer",
    "name": "Workflow Optimizer",
    "description": "Expert process improvement specialist focused on analyzing, optimizing, and automating workflows across all business functions for maximum productivity and efficiency",
    "color": "#2ECC71",
    "emoji": "👤",
    "division": "Product",
    "mode": "subagent"
  },
  {
    "id": "account-strategist",
    "name": "Account Strategist",
    "description": "Expert post-sale account strategist specializing in land-and-expand execution, stakeholder mapping, QBR facilitation, and net revenue retention. Turns closed deals into long-term platform relationships through systematic expansion planning and multi-threaded account development.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Sales",
    "mode": "subagent"
  },
  {
    "id": "brand-guardian",
    "name": "Brand Guardian",
    "description": "Expert brand strategist and guardian specializing in brand identity development, consistency maintenance, and strategic brand positioning",
    "color": "#3498DB",
    "emoji": "🛡️",
    "division": "Sales",
    "mode": "subagent"
  },
  {
    "id": "cultural-intelligence-strategist",
    "name": "Cultural Intelligence Strategist",
    "description": "CQ specialist that detects invisible exclusion, researches global context, and ensures software resonates authentically across intersectional identities.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Sales",
    "mode": "subagent"
  },
  {
    "id": "data-consolidation-agent",
    "name": "Data Consolidation Agent",
    "description": "AI agent that consolidates extracted sales data into live reporting dashboards with territory, rep, and pipeline summaries",
    "color": "#6B7280",
    "emoji": "📈",
    "division": "Sales",
    "mode": "subagent"
  },
  {
    "id": "deal-strategist",
    "name": "Deal Strategist",
    "description": "Senior deal strategist specializing in MEDDPICC qualification, competitive positioning, and win planning for complex B2B sales cycles. Scores opportunities, exposes pipeline risk, and builds deal strategies that survive forecast review.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Sales",
    "mode": "subagent"
  },
  {
    "id": "discovery-coach",
    "name": "Discovery Coach",
    "description": "Coaches sales teams on elite discovery methodology — question design, current-state mapping, gap quantification, and call structure that surfaces real buying motivation.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Sales",
    "mode": "subagent"
  },
  {
    "id": "korean-business-navigator",
    "name": "Korean Business Navigator",
    "description": "Korean business culture for foreign professionals — 품의 decision process, nunchi reading, KakaoTalk business etiquette, hierarchy navigation, and relationship-first deal mechanics",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Sales",
    "mode": "subagent"
  },
  {
    "id": "outbound-strategist",
    "name": "Outbound Strategist",
    "description": "Signal-based outbound specialist who designs multi-channel prospecting sequences, defines ICPs, and builds pipeline through research-driven personalization — not volume.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Sales",
    "mode": "subagent"
  },
  {
    "id": "paid-media-auditor",
    "name": "Paid Media Auditor",
    "description": "Comprehensive paid media auditor who systematically evaluates Google Ads, Microsoft Ads, and Meta accounts across 200+ checkpoints spanning account structure, tracking, bidding, creative, audiences, and competitive positioning. Produces actionable audit reports with prioritized recommendations and projected impact.",
    "color": "#F39C12",
    "emoji": "🤖",
    "division": "Sales",
    "mode": "subagent"
  },
  {
    "id": "pipeline-analyst",
    "name": "Pipeline Analyst",
    "description": "Revenue operations analyst specializing in pipeline health diagnostics, deal velocity analysis, forecast accuracy, and data-driven sales coaching. Turns CRM data into actionable pipeline intelligence that surfaces risks before they become missed quarters.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Sales",
    "mode": "subagent"
  },
  {
    "id": "report-distribution-agent",
    "name": "Report Distribution Agent",
    "description": "AI agent that automates distribution of consolidated sales reports to representatives based on territorial parameters",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Sales",
    "mode": "subagent"
  },
  {
    "id": "sales-coach",
    "name": "Sales Coach",
    "description": "Expert sales coaching specialist focused on rep development, pipeline review facilitation, call coaching, deal strategy, and forecast accuracy. Makes every rep and every deal better through structured coaching methodology and behavioral feedback.",
    "color": "#6B7280",
    "emoji": "💼",
    "division": "Sales",
    "mode": "subagent"
  },
  {
    "id": "sales-data-extraction-agent",
    "name": "Sales Data Extraction Agent",
    "description": "AI agent specialized in monitoring Excel files and extracting key sales metrics (MTD, YTD, Year End) for internal live reporting",
    "color": "#6B7280",
    "emoji": "💼",
    "division": "Sales",
    "mode": "subagent"
  },
  {
    "id": "study-abroad-advisor",
    "name": "Study Abroad Advisor",
    "description": "Full-spectrum study abroad planning expert covering the US, UK, Canada, Australia, Europe, Hong Kong, and Singapore — proficient in undergraduate, master's, and PhD application strategy, school selection, essay coaching, profile enhancement, standardized test planning, visa preparation, and overseas life adaptation, helping Chinese students craft personalized end-to-end study abroad plans.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Sales",
    "mode": "subagent"
  },
  {
    "id": "supply-chain-strategist",
    "name": "Supply Chain Strategist",
    "description": "Expert supply chain management and procurement strategy specialist — skilled in supplier development, strategic sourcing, quality control, and supply chain digitalization. Grounded in China's manufacturing ecosystem, helps companies build efficient, resilient, and sustainable supply chains.",
    "color": "#3498DB",
    "emoji": "🤖",
    "division": "Sales",
    "mode": "subagent"
  },
  {
    "id": "xr-cockpit-interaction-specialist",
    "name": "XR Cockpit Interaction Specialist",
    "description": "Specialist in designing and developing immersive cockpit-based control systems for XR environments",
    "color": "#F39C12",
    "emoji": "👓",
    "division": "Spatial Computing",
    "mode": "subagent"
  },
  {
    "id": "french-consulting-market-navigator",
    "name": "French Consulting Market Navigator",
    "description": "Navigate the French ESN/SI freelance ecosystem — margin models, platform mechanics (Malt, collective.work), portage salarial, rate positioning, and payment cycle realities",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Support",
    "mode": "subagent"
  },
  {
    "id": "identity-graph-operator",
    "name": "Identity Graph Operator",
    "description": "Operates a shared identity graph that multiple AI agents resolve against. Ensures every agent in a multi-agent system gets the same canonical answer for \"who is this entity?\" - deterministically, even under concurrent writes.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Support",
    "mode": "subagent"
  },
  {
    "id": "model-qa-specialist",
    "name": "Model QA Specialist",
    "description": "Independent model QA expert who audits ML and statistical models end-to-end - from documentation review and data reconstruction to replication, calibration testing, interpretability analysis, performance monitoring, and audit-grade reporting.",
    "color": "#6B7280",
    "emoji": "👤",
    "division": "Support",
    "mode": "subagent"
  },
  {
    "id": "api-tester",
    "name": "API Tester",
    "description": "Expert API testing specialist focused on comprehensive API validation, performance testing, and quality assurance across all systems and third-party integrations",
    "color": "#9B59B6",
    "emoji": "🧪",
    "division": "Testing",
    "mode": "subagent"
  },
  {
    "id": "git-workflow-master",
    "name": "Git Workflow Master",
    "description": "Expert in Git workflows, branching strategies, and version control best practices including conventional commits, rebasing, worktrees, and CI-friendly branch management.",
    "color": "#F39C12",
    "emoji": "👤",
    "division": "Testing",
    "mode": "subagent"
  },
  {
    "id": "jira-workflow-steward",
    "name": "Jira Workflow Steward",
    "description": "Expert delivery operations specialist who enforces Jira-linked Git workflows, traceable commits, structured pull requests, and release-safe branch strategy across software teams.",
    "color": "#F39C12",
    "emoji": "👤",
    "division": "Testing",
    "mode": "subagent"
  },
  {
    "id": "test-results-analyzer",
    "name": "Test Results Analyzer",
    "description": "Expert test analysis specialist focused on comprehensive test result evaluation, quality metrics analysis, and actionable insight generation from testing activities",
    "color": "#6366F1",
    "emoji": "🧪",
    "division": "Testing",
    "mode": "subagent"
  }
]

export const agents = [
  ...primaryAgents,
  ...commandAgents,
  ...subAgents,
]

export type Agent = typeof agents[number]
