// Session and Project data types
// Generated by Analytics Reporter + Backend Architect

// Opencode session message structure
export interface SessionMessage {
  info: {
    id: string
    sessionID: string
    role: 'user' | 'assistant' | 'system'
    time: {
      created: number
      completed?: number
    }
    agent: string
    modelID?: string
    providerID?: string
    mode?: string
    parentID?: string
    path?: {
      cwd: string
      root: string
    }
    cost?: number
    tokens?: {
      total: number
      input: number
      output: number
      reasoning?: number
      cache?: {
        read: number
        write: number
      }
    }
    finish?: string
    summary?: {
      diffs: any[]
    }
  }
  parts: Array<{
    id: string
    sessionID: string
    messageID: string
    type: 'text' | 'reasoning' | 'tool' | 'step-start'
    text?: string
    callID?: string
    tool?: string
    state?: any
    snapshot?: string
    time?: {
      start: number
      end: number
    }
  }>
}

// Opencode session list item (from /session endpoint)
export interface SessionListItem {
  id: string
  slug: string
  projectID: string
  directory: string
  title: string
  version: string
  summary?: {
    additions: number
    deletions: number
    files: number
  }
  time: {
    created: number
    updated: number
  }
}

// Processed session with messages
export interface Session extends SessionListItem {
  messages: SessionMessage[]
}

// Project extracted from sessions
export interface Project {
  path: string              // Full directory path
  name: string              // Project name (from path)
  sessions: string[]        // Session IDs in this project
  agents: string[]          // Agent IDs used in this project
  lastUpdated: number       // Timestamp of last update
  sessionCount: number      // Total number of sessions
}

// Agent activity in a project
export interface ProjectAgentActivity {
  agentId: string
  sessionCount: number      // Number of sessions with this agent
  messageCount: number      // Total messages with this agent
  lastActive: number        // Last activity timestamp
  isActive: boolean         // Active in last 24 hours
}

// Project with agent activity details
export interface ProjectWithActivity extends Project {
  agentActivity: ProjectAgentActivity[]
}

// Conversation between user and a specific agent in a project
export interface ProjectConversation {
  projectId: string
  agentId: string
  messages: Array<{
    role: 'user' | 'assistant'
    content: string
    timestamp: Date
    sessionId: string
    messageId: string
  }>
}

// Agent status in a project
export type AgentStatus = 'active' | 'historical'

// Agent in project context
export interface ProjectAgent {
  id: string
  name: string
  description: string
  division: string
  color: string
  emoji: string
  status: AgentStatus
  lastActive?: number
  messageCount?: number
}
